### ISSUE TITLE
openjdk10 can cause RuneLite application to freeze

### ISSUE THREAD

**Issue by deathbeam** [flathub/net.runelite.RuneLite#1]
Hello, just randomly stumbled upon this, but I noticed that openjdk10 is declared as dependency for RuneLite. Running openjdk10 is on the list of known issues [here](https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#client-freezing) that can cause client to freeze.

Here is also related issue in RL issue tracker: https://github.com/runelite/runelite/issues/3999

**Comment by mbooth101** [comment]
Hi, sorry to barge in -- I recently update openjdk10 in Flathub to 10.0.2, so consider rebuilding against the latest build of openjdk10 and org.freedesktop.Platform 18.08 to see if that helps.

FWIW, it might be worth trying openjdk11 since I just updated it in Flathub to 11.0.1 -- so hopefully they smoothed out any rough edges a bit with the point release :-)

BTW, since Java 11 is the new long-term support version, I have no plans to build Java 8 for Flathub.

**Comment by rushsteve1** [comment]
Ok this took forever, and I apologize for that, but the flatpak has been updated to RuneLite 2.0.0 which should fix this issue.
