### ISSUE TITLE
.dat client files are not being created

### ISSUE THREAD

**Issue by jorgeluiscarrillo** [flathub/net.runelite.RuneLite#9]
I don't know if this is intentional, but I noticed the two .dat files that are normally created by the client `jagex_cl_oldschool_LIVE.dat` and `random.dat` are showing up as empty directories in `~/.var/app/net.runelite.RuneLite/`.

There are no noticeable issues so I don't think they are crucial to the client, however I am a bit paranoid since it seems no one knows the exact purpose of these files. I would feel safer knowing that these files were left alone. Im not too experienced with flatpak so I don't know if there was some oversight with the persist option when they were added in 9e20506d763326b046408bdb4c3991d53796f83a.

**Comment by AsciiWolf** [comment]
Yeah, `--persist` only works for directories.

/cc @rushsteve1

**Comment by rushsteve1** [comment]
Interesting, I didn't know that. [The documentation](https://docs.flatpak.org/en/latest/flatpak-command-reference.html?highlight=persist#) doesn't mention it either.
@AsciiWolf is there a recommended approach to persisting specific files? Or should I simply not persist them since these files are apparently(?) not necessary for it to function?

**Comment by AsciiWolf** [comment]
As far as I know, it is unfortunately not possible to easily make files persistent, only directories. You may try asking @nedrichards or someone else who could know more about this. :)
